use_frameworks!

platform :ios, '8.0'

target 'XIMOneControllerCategoryKit_Example' do
  pod 'XIMOneControllerCategoryKit', :path => '../'

  target 'XIMOneControllerCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
